### ISSUE TITLE
Empty repository 

### ISSUE THREAD

**Issue by mohsenuss91** [anitabenites/myfirstwebsite#2]
No files.

**Comment by anitabenites** [comment]
yes, I do not know what is happening but it is getting difficult to update from my local repository to the remote repository my code!

**Comment by anitabenites** [comment]
do you perhaps knows the exactly steps that I have to write in my terminal? i have already a local repository and a git in my computer.

**Comment by mohsenuss91** [comment]
@anitabenites Ok, check out this :+1: 

https://try.github.io

https://www.youtube.com/watch?v=U8GBXvdmHT4

https://www.youtube.com/watch?v=0fKg7e37bQE

**Comment by anitabenites** [comment]
great!! thank you, very much!!!! 
I will take a look at it and let you know.

**Comment by anitabenites** [comment]
great!, thank you very much for your help! 
I will let you know once I finished and hopefully I will push my code into the github.
Thanks :+1:
